baseURL = 'https://huynambka.github.io/'
languageCode = 'vn'
title = 'shibajutsu'
theme = 'archie'
copyright = "© shibajutsu"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = "toggle"
useCDN = false
subtitle = "Dối lòng sẽ bị quạ bắt diều hâu tha"
customCSS = ["css/custom.css"]
mathjax = true # enable MathJax support
katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/huynambka"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/huynambka/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4