baseURL = 'https://huynambka.github.io/'
languageCode = 'en-us'
title = 'shibajutsu'
theme = 'archie'
copyright = "© shibajutsu"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = "auto"
useCDN = false
subtitle = "Welcome to my personal website"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
