baseURL = 'https://huynambka.github.io/'
languageCode = 'vn'
title = 'shibajutsu'
theme = 'archie'
copyright = "© shibajutsu"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode = "dark"
useCDN = false
subtitle = "Dối lòng sẽ bị quạ bắt diều hâu tha"
customCSS = ["css/custom.css"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
